"""
QiskitSage Renderer
Converts ReviewResult to GitHub-flavored markdown review comment.
"""

from .models import ReviewResult, Severity, Category


class Renderer:
    """Generates GitHub markdown from review results."""

    def __init__(self):
        self.header = "## QiskitSage AI Review\n\n"
        self.footer = "\n\n---\n*Review generated by QiskitSage*"

    def render(self, result: ReviewResult) -> str:
        """
        Convert ReviewResult to GitHub markdown string.
        """
        lines = [self.header]

        # Summary section
        lines.append(self._generate_summary(result))
        lines.append("")

        # Findings section (if any)
        if result.findings:
            lines.append(self._generate_findings(result.findings))
            lines.append("")
        else:
            lines.append("[OK] **No issues detected in this PR.**")
            lines.append("")

        # Risk indicators
        if result.semantic_regression_detected:
            lines.append("[ERROR] **REGRESSION DETECTED**: Semantic probe detected behavior change!")
            lines.append("")

        if result.ffi_risk_detected:
            lines.append("[WARNING] **FFI RISK**: Rust unsafe patterns detected in changed code!")
            lines.append("")

        lines.append(self.footer)
        return "".join(lines)

    def _generate_summary(self, result: ReviewResult) -> str:
        """Generate summary section."""
        lines = []

        lines.append(f"**PR:** {result.pr_url} (#{result.pr_number})")
        lines.append("")

        # Statistics
        stats = []
        if result.critical_count > 0:
            stats.append(f"[ERROR] **Critical:** {result.critical_count}")
        if result.high_count > 0:
            stats.append(f"[WARNING] **High:** {result.high_count}")
        if result.total_findings > 0:
            stats.append(f"[INFO] **Total:** {result.total_findings} findings")

        if stats:
            lines.append(" | ".join(stats))
        else:
            lines.append("[INFO] **Total:** 0 findings")

        lines.append("")
        lines.append(f"**Agents:** {', '.join(result.agents_run) if result.agents_run else 'None'}")
        lines.append(f"**Execution time:** {result.execution_time_seconds:.1f}s")

        return "\n".join(lines)

    def _generate_findings(self, findings) -> str:
        """Generate detailed findings section."""
        lines = ["### Detailed Findings\n\n"]

        # Group by severity
        by_severity = {}
        for finding in findings:
            if finding.severity not in by_severity:
                by_severity[finding.severity] = []
            by_severity[finding.severity].append(finding)

        # Display in severity order
        severity_order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]
        for severity in severity_order:
            if severity in by_severity:
                lines.append(f"#### {severity.value} Severity\n\n")
                for finding in by_severity[severity]:
                    lines.append(self._format_finding(finding))
                    lines.append("")

        return "".join(lines)

    def _format_finding(self, finding) -> str:
        """Format a single finding."""
        lines = []

        # Header with file location
        location = f"{finding.file}:{finding.line}" if finding.line else finding.file
        lines.append(f"**{finding.title}**  ")
        lines.append(f"Location: `{location}`  ")
        lines.append(f"Agent: `{finding.agent_id}` | Confidence: `{finding.confidence:.0%}`  ")
        lines.append("")

        # Description
        if finding.description:
            lines.append(finding.description)
            lines.append("")

        # Suggestion
        if finding.suggestion:
            lines.append(f"**[SUGGESTION]** {finding.suggestion}")
            lines.append("")

        # Evidence
        if finding.evidence:
            lines.append("**Evidence:**")
            lines.append("```")
            lines.append(finding.evidence[:200])  # Truncate long evidence
            lines.append("```")
            lines.append("")

        # Special metadata
        if finding.category == Category.SEMANTIC and finding.fidelity_before and finding.fidelity_after:
            lines.append(f"**Fidelity:** {finding.fidelity_before:.4f} -> {finding.fidelity_after:.4f}")
            lines.append("")

        return "\n".join(lines)
